# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af705ff5afd58c3514467f867923b01c65e409bc21f48bd572ffd9a66de47fbb526a2900c08cbc31710a0d84ed9a652881fc7f2baf77745f2473516c2efacf65

test:
  secret_key_base: 51b0d10555c46e47a059e8d69c5a8b38b2dff909be395387bb6b385882dc236836725eddaaf247f4dea1cdffb317829bac6d36e951f53cf627099cc04d514776

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
